apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-clm
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: influxdb
 labels:
  app: influxdb
spec:
 replicas: 1
 selector:
  matchLabels:
   app: influxdb
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
    app: influxdb
  spec:
   restartPolicy: Always
   containers:
   - name: influxdb
     image: influxdb_img
     imagePullPolicy: Never
     ports:
     - containerPort: 8086
       name: influxdb
     livenessProbe:
       exec:
        command:
         - sh
         - livenessprobe.sh
       initialDelaySeconds: 15
       periodSeconds: 3
     volumeMounts:
      - name: influxdb-vol
        mountPath: /var/lib/influxdb
   volumes:
     - name: influxdb-vol
       persistentVolumeClaim:
         claimName: influxdb-pv-clm
---
apiVersion: v1
kind: Service
metadata:
 name: influxdb-service
spec:
 type: ClusterIP
 selector:
  app: influxdb
 ports:
 - protocol: TCP
   port: 8086
# Don't need this ?
   targetPort: 8086
   name: influxdb-service-port
