#METALLB
apiVersion: v1
kind: ConfigMap
metadata:
 namespace: metallb-system
 name: config
data:
 config: |
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - node_ip-node_ip
# this range was copy pasted for testing, should automatically be the NodeIP
# see IamLena's work
