apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-vol-clm
 labels:
  app: mysql-app
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
spec:
 selector:
  matchLabels:
   app: mysql-app
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
     app: mysql-app
  spec:
   restartPolicy: Always
   containers:
   - name: mysql
     image: mysql_img:latest
     imagePullPolicy: Never
     ports:
     - containerPort: 3306
       name: mysql
     env:
     - name: ADMIN_WP_USER
       valueFrom:
        configMapKeyRef:
         name: my-vars
         key: wp_admin
     - name: ADMIN_WP_PASS
       valueFrom:
        configMapKeyRef:
         name: my-vars
         key: wp_admin_pass
     - name: DB_USER
       valueFrom:
        configMapKeyRef:
         name: my-vars
         key: wp_user1
     - name: DB_PASSWORD
       valueFrom:
        configMapKeyRef:
         name: my-vars
         key: wp_u1_pass
     livenessProbe:
      exec:
       command:
       - sh
       - livenessprobe.sh
      initialDelaySeconds: 30
      periodSeconds: 3
     volumeMounts:
     - name: mysql-vol
       mountPath: /var/lib/mysql
   volumes:
   - name: mysql-vol
     persistentVolumeClaim:
      claimName: mysql-vol-clm
---
apiVersion: v1
kind: Service
metadata:
 name: mysql-service
 labels:
  app: mysql-app
spec:
 selector:
  app: mysql-app
 type: ClusterIP
 ports:
 - port: 3306
   name: mysql
