apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-vol-clm
  labels:
    app: mariadb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      restartPolicy: Always
      containers:
      - name: mariadb
        image: mysql_img:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: ADMIN_WP_USER
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_admin
        - name: ADMIN_WP_PASS
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_admin_pass
        - name: DB_USER
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_user1
 #         value: "wp_user"
        - name: DB_PASSWORD
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_u1_pass
        livenessProbe:
            exec:
              command:
                - sh
                - livenessprobe.sh
            initialDelaySeconds: 30
            periodSeconds: 3
        volumeMounts:
        - name: mariadb-vol
          mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-vol-clm
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mariadb-app
spec:
  selector:
    app: mariadb-app
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql
