#BASIC ALPINE
FROM alpine:latest


# apk add telegraf and possibly screen too
# we are starting from scratch...
RUN	apk update

RUN	apk add --no-cache telegraf screen


# i think openrc is how i get to use service, as in service nginx start
# might as well do both of these here
#RUN apk add openrc openssl

