apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
  app: nginx
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   restartPolicy: Always
   containers:
   - name: nginx
     image: nginx_img
     imagePullPolicy: Never
     ports:
     - containerPort: 80
     - containerPort: 443
     livenessProbe:
       httpGet:
        path: /
        port: 80
       initialDelaySeconds: 30
       periodSeconds: 5
     env:
     - name: INFLUX_DB
       value: influxdb-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 annotations:
  metallb.universe.tf/allow-shared-ip: metallb
#  metaldb.universe.tf/allow-shared-ip: shared
spec:
 type: LoadBalancer
 selector:
  app: nginx
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
   name: nginx-service-port
 - protocol: TCP
   port: 443
   targetPort: 443
   name: nginx-service-ssl-port
