apiVersion: apps/v1
kind: Deployment
metadata:
 name: phpmyadmin
 labels:
  app: phpmyadmin
spec:
 replicas: 1
 selector:
  matchLabels:
   app: phpmyadmin
 template:
  metadata:
   labels:
    app: phpmyadmin
  spec:
   restartPolicy: Always
   containers:
   - name: phpmyadmin
     image: phpmyadmin_img
     imagePullPolicy: Never
     ports:
     - containerPort: 5000
     livenessProbe:
       httpGet:
        path: /
        port: 5000
       initialDelaySeconds: 30
       periodSeconds: 5
     #     env:
#     - name: INFLUX_DB
#       value: influxdb-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin-service
 annotations:
  metallb.universe.tf/allow-shared-ip: metallb
#  metallb.universe.tf/allow-shared-ip: sharing key
#  metallb.universe.tf/allow-shared-ip: shared
spec:
 type: LoadBalancer
 selector:
  app: phpmyadmin
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
   name: phpmyadmin-service-port
