apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
 labels:
  app: wordpress
spec:
 replicas: 1
 selector:
  matchLabels:
   app: wordpress
 template:
  metadata:
   labels:
    app: wordpress
  spec:
   containers:
   - name: wordpress
     image: wordpress_img
     imagePullPolicy: Never
     ports:
     - containerPort: 5050
     env:
     - name: INFLUX_DB
       value: influxdb-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
 name: wordpress-service
 annotations:
  metaldb.universe.tf/allow-shared-ip: shared
spec:
 type: LoadBalancer
 selector:
  app: wordpress
 ports:
 - protocol: TCP
   port: 5050
   targetPort: 5050
   name: wordpress-service-port
