# Celia's that i modified a lot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      restartPolicy: Always
      containers:
      - image: wordpress_img
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: DB_NAME
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_db_name 
        - name: ADMIN_WP_USER
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_admin
        - name: ADMIN_WP_PASS
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_admin_pass
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_user1
 #         value: "wp_user"
        - name: DB_PASSWORD
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_u1_pass
        - name: DB_USER2
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_user2
        - name: DB_PASSWORD2
          valueFrom:
           configMapKeyRef:
            name: my-vars
            key: wp_u2_pass
        - name: NODE_IP
          valueFrom:
           fieldRef:
            fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress-svc
  labels:
    app: wordpress-app
spec:
  selector:
    app: wordpress-app
  ports:
    - port: 5050
      targetPort: 5050
      name: http
  type: LoadBalancer
