apiVersion: 1
datasources:
  - name: Monitoring
    type: influxdb
    access: proxy
    orgId: 1
    url: $DB_URL
    # <string> database name, if used
    database: $DB_NAME
    # <bool> enable/disable basic auth
    basicAuth: true
    # <string> basic auth username
    basicAuthUser: admin
    # <string> Deprecated, use secureJsonData.basicAuthPassword
    basicAuthPassword: admin
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false