apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps
spec:
 selector:
  matchLabels:
   app: ftps-app
 template:
  metadata:
   labels:
    app: ftps-app
  spec:
   containers:
   - name: ftps-app
     image: ftps_img
     imagePullPolicy: Never
     ports:
     - containerPort: 21
     - containerPort: 20
     - containerPort: 30020
     - containerPort: 30021
     - containerPort: 30022
     livenessProbe:
      exec:
       command:
       - sh
       - livenessprobe.sh
      periodSeconds: 3
      initialDelaySeconds: 10
     env:
     - name: NODE_IP
       valueFrom:
        fieldRef:
         fieldPath: status.hostIP
     - name: FTP_USER
       value: "user"
     - name: FTP_PASSWORD
       value: "password"
---
apiVersion: v1
kind: Service
metadata:
 name: ftps
 annotations:
  metallb.universe.tf/allow-shared-ip: shared
spec:
 type: LoadBalancer
 ports:
 - name: ftp
   port: 21
   targetPort: 21
   protocol: TCP
 - name: ftpactive
   port: 20
   targetPort: 20
   protocol: TCP
 - name: ftp30020
   port: 30020
   targetPort: 30020
   protocol: TCP
 - name: ftp30021
   port: 30021
   targetPort: 30021
   protocol: TCP
 - name: ftp30022
   port: 30022
   targetPort: 30022
   protocol: TCP
 selector:
  app: ftps-app