apiVersion: apps/v1
kind: Deployment
metadata:
 name: ftps
 labels:
  app: ftps
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ftps
 template:
  metadata:
   labels:
    app: ftps
  spec:
   containers:
   - name: ftps
     image: ftps_img
     imagePullPolicy: Never
     ports:
     - containerPort: 20
     - containerPort: 21
     - containerPort: 7777
     env:
     - name: INFLUX_IP
       value: influxdb-service.default.svc.cluster.local
     - name: NODE_IP
        value: ftps-service.default.svc.cluster.local
     livenessProbe:
      exec:
       command:
       - pgrep
       - vsftpd
     volumeMounts:
     - mountPath: "/home/"
       subPath: "ftps"
       name: ftps-vol
   volumes:
   - name: ftps-vol
     persistentVolumeClaim:
      claimName: ftps-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
 name: ftps-service
 annotations:
  metallb.universe.tf/allow-shared-ip: metallb
#  metallb.universe.tf/allow-shared-ip: shared
spec:
 type: LoadBalancer
 selector:
  app: ftps
 ports:
 - protocol: TCP
   port: 20
   targetPort: 20
   name: ftps-service-data-port
 - protocol: TCP
   port: 21
   targetPort: 21
   name: ftps-service-port
 - protocol: TCP
   port: 7777
   targetPort: 7777
   name: ftps-service-passv-port
