apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
  app: nginx
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
   - name: nginx
     image: nginx_img
     imagePullPolicy: Never
     ports:
     - containerPort: 80
     - containerPort: 443
     env:
     - name: INFLUX_DB
       value: influxdb-service.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 annotations:
  metaldb.universe.tf/allow-shared-ip: entrypoint
spec:
 type: LoadBalancer
 selector:
  app: nginx
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
   name: nginx-service-port
 - protocol: TCP
   port: 443
   targetPort: 443
   name: nginx-service-ssl-port
